### PR TITLE
fix API issues with latest sveltekit

### PR DESCRIPTION
**Pull request by orefalo**
Took me some serious amount of time to get the api aligned - thought it would help others.

...and yes, I was a Svelte newbie

### CODE REVIEW

**Comment by benwoodward** [comment]
Thanks so much for this! I upgraded SvelteKit and was in the same world of confusion. Saved me a good few hours.

**Comment by Vanderscycle** [comment]
@orefalo solved the issue on my end as before I kept getting 500 errors. 
Thank you for making the corrections

**Comment by benwoodward** [comment]
@srmullen I think you should merge this

**Comment by orefalo** [comment]
thank you

**Pull request merged**
